baseURL = 'https://vrslev.com'
languageCode = 'en'
title = 'vrslev'
theme = "hugo-coder"
enableEmoji = true


[markup.highlight]
style = "gruvbox"

[params]
author = "Lev Vereshchagin"
info = "Python Developer"
description = "Lev Vereshchagin's personal website"
keywords = "blog,developer,personal"
avatarUrl = "https://avatars.githubusercontent.com/u/75225148"
since = 2024
enableTwemoji = true
colorScheme = "auto"
hideColorSchemeToggle = true

[taxonomies]
tag = "tags"

[[params.social]]
name = "GitHub"
icon = "fa-brands fa-github fa-2x"
weight = 1
url = "https://github.com/vrslev"
[[params.social]]
name = "Telegram"
icon = "fa-brands fa-telegram fa-2x"
weight = 2
url = "https://t.me/vrslev"
[[params.social]]
name = "Mail"
icon = "fa-regular fa-envelope fa-2x"
weight = 3
url = "mailto:mail@vrslev.com"

[[menu.main]]
name = "Blog"
weight = 1
url = "posts/"
